disabled_rules:
  - trailing_whitespace

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

opt_in_rules:
  - indentation_width
  - empty_string
  - empty_xctest_method
  - no_empty_block
  - no_magic_numbers
  - attribute_name_spacing
  - function_parameter_count
