name: SwiftLint

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run SwiftLint
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          echo 'Setting up Homebrew...'
          brew update

      - name: Install SwiftLint
        run: |
          echo 'Installing SwiftLint...'
          brew install swiftlint

      - name: Run SwiftLint
        run: |
          echo 'Running SwiftLint...'
          swiftlint lint --strict

      - name: Annotate SwiftLint issues
        if: failure()
        run: |
          echo "::error file=$file,line=$line,col=$col::$message"
