name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode_14.2.app # Cambia la ruta si usas otra versión
        sudo xcodebuild -runFirstLaunch

    - name: Install missing simulators
      run: |
        # Comando para instalar simuladores de iOS específicos si es necesario
        xcode-select --switch /Applications/Xcode_14.2.app
        sudo xcodebuild -installDeployment -sdk iphoneos

    - name: Build and test
      run: |
        xcodebuild clean build -scheme CheckPointList -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 15 Pro'
