name: iOS Build and Test

on:
  push:
    branches:
      - '**'

jobs:
          
  lint:
    name: Run SwiftLint
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          echo 'Setting up Homebrew...'
          brew update

      - name: Install SwiftLint
        run: |
          echo 'Installing SwiftLint...'
          brew install swiftlint

      - name: Run SwiftLint
        run: |
          echo 'Running SwiftLint...'
          swiftlint lint --strict

      - name: Annotate SwiftLint issues
        if: failure()
        run: |
          echo "::error file=$file,line=$line,col=$col::$message"

  Unit:
    name: Run Unit Tests
    runs-on: macos-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set Xcode version to 16.2
        run: sudo xcode-select --switch /Applications/Xcode_16.2.app

      - name: Install iOS Simulator 18.2
        run: xcodebuild -downloadPlatform iOS -verbose 

      - name: Create iOS 18.2 Simulator
        run: xcrun simctl create "iPhone 15 Pro (iOS 18.2)" com.apple.CoreSimulator.SimDeviceType.iPhone-15-Pro com.apple.CoreSimulator.SimRuntime.iOS-18-2
      
      - name: Run Tests
        run: |
          xcodebuild test \
            -scheme CheckPointList \
            -destination 'platform=iOS Simulator,OS=18.2,name=iPhone 15 Pro (iOS 18.2)'
            -enableCodeCoverage YES

      - name: Shutdown iOS Simulator
        run: xcrun simctl shutdown all

  Coverage:
    name: Run Slather Report
    runs-on: macos-latest
    needs: Unit

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.6'

      - name: Install Slather
        run: |
          gem install slather

      - name: Run Slather coverage
        run: |
          slather