name: XCTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ios:
    runs-on: macos-latest

    steps:

    - name: List available simulators
      run: xcrun simctl list devices
    
    - name: Set up Xcode 16.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
          xcode-version: '16.2'

    - name: see version xcode
      run: xcodebuild -version

    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Run tests on iPhone 14 Simulator with iOS 16.0
    - name: Run Tests on iPhone 14 Simulator (iOS 16.0)
      run: |
        xcodebuild test \
          -scheme 'CheckPointList' \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0'