name: iOS Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Xcode version to 16.2
        run: sudo xcode-select --switch /Applications/Xcode_16.2.app

      - name: Print Xcode version
        run: xcodebuild -version

      - name: Install iOS 17.0 Simulator
        run: |
          xcrun simctl create "iPhone 15 Pro (iOS 18.2)" com.apple.CoreSimulator.SimDeviceType.iPhone-15-Pro com.apple.CoreSimulator.SimRuntime.iOS-18-2
      
