name: XCTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ios:
    runs-on: macos-latest

    steps:

    - name: see version xcode
      run: xcodebuild -version
      
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Run tests on iPhone 14 Simulator with iOS 16.0
    - name: Run Tests on iPhone 14 Simulator (iOS 16.0)
      run: |
        xcodebuild test \
          -scheme 'Requestify' \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0'